name: Python-Version-Check

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: mkdir -p result

      - name: Display Python version
        run: python -c "import sys; print(sys.version)" > result/python-version-${{ matrix.python-version }}.txt
      - uses: actions/upload-artifact@v3
        with:
          name: python-version-check-result
          path: result/python-version-${{ matrix.python-version }}.txt
      - name: Store the result
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b python-version-${{ matrix.python-version }}
          git add -A
          git commit -m "Add Python ${- matrix.python-version} output"
          git push origin python-version-${{ matrix.python-version }}
